### ISSUE TITLE
Dataset loading problem

### ISSUE THREAD

**Issue by JunsFu** [declare-lab/Multimodal-Infomax#18]
Hello, first of all thank you for your hard work!
My question is: after downloading the MOSI data set, I encountered this problem during the loading of the data set:
Traceback (most recent call last):
   File "F:/MLP/2023_Summer/Git/MMIM/src/main.py", line 57, in <module>
     solver.train_and_eval()
   File "F:\MLP\2023_Summer\Git\MMIM\src\solver.py", line 281, in train_and_eval
     train_loss = train(model, optimizer_main, criterion, 1)
   File "F:\MLP\2023_Summer\Git\MMIM\src\solver.py", line 128, in train
     for i_batch, batch_data in enumerate(self.train_loader):
   File "F:\Anaconda\envs\self_mm\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
     data = self._next_data()
   File "F:\Anaconda\envs\self_mm\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
     data = self._dataset_fetcher.fetch(index) # may raise StopIteration
   File "F:\Anaconda\envs\self_mm\lib\site-packages\torch\utils\data\_utils\fetch.py", line 47, in fetch
     return self.collate_fn(data)
   File "F:\MLP\2023_Summer\Git\MMIM\src\data_loader.py", line 135, in collate_fn
     bert_sentences = torch.LongTensor([sample["input_ids"] for sample in bert_details])
ValueError: expected sequence of length 50 at dim 1 (got 39)
![image](https://github.com/declare-lab/Multimodal-Infomax/assets/100461491/3031e7fb-eab9-4cf5-ab17-60ac92d00161)

**Comment by Clement25** [comment]
can you remove 
https://github.com/declare-lab/Multimodal-Infomax/blob/cd0774c5a712ca5f1a5497dbf27dde11cade7434/src/data_loader.py#L131

'truncation=True' and see how it works

**Comment by JunsFu** [comment]
Thank you for your reply. I have done what you said but the same problem still occurs.
![image](https://github.com/declare-lab/Multimodal-Infomax/assets/100461491/95944e1e-207d-43f0-9aa6-61de08a64f1f)

**Comment by JunsFu** [comment]
I found the reason. The version of transformers is wrong and I need to use version 4.0.
